

name: CI
on: [push]
env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

jobs:
  lighthouse-audit:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn' # or 'npm'

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile --prefer-offline

      - name: yarn install, build
        run: |
          yarn install
          yarn build

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: './lighthouserc.json'
          runs: 5
          temporaryPublicStorage: true

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create and configure .env.development for Contentful
        run: |
          touch .env.development && echo {\"CONTENTFUL_SPACE_ID\": \"${CONTENTFUL_SPACE_ID}\", \"CONTENTFUL_ACCESS_TOKEN\": \"${CONTENTFUL_ACCESS_TOKEN}\"} > .env.development

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          wait-on: http://localhost:9000

  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm' # or 'npm'
      - run: npm ci
      - run: npm build --if-present
      - run: npm serve & npx wait-on http://localhost:9000
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:9000 --exit
