

name: CI
on: [pull_request]
env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  GATSBY_ALGOLIA_APP_ID: ${{secrets.GATSBY_ALGOLIA_APP_ID}}
  GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
  ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}

jobs:
  report:
    runs-on: ubuntu-latest
      steps:
        - uses: craftech-io/slack-action@v1
          with:
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            slack_channel: general
            slack_username: Github
          if: always()
  lighthouse-audit:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: 'yarn' # or 'npm'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install, build
        run: |
          yarn install
          yarn build

      # - name: run Lighthouse CI
      #   run: |
      #     npm install -g @lhci/cli@0.8.x
      #     lhci autorun

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true,
          runs: 5
          temporaryPublicStorage: true

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Create and configure .env.development for Contentful
  #       run: |
  #         touch .env.development && echo {\"CONTENTFUL_SPACE_ID\": \"${CONTENTFUL_SPACE_ID}\", \"CONTENTFUL_ACCESS_TOKEN\": \"${CONTENTFUL_ACCESS_TOKEN}\"} > .env.development

  #     # Run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         build: yarn build
  #         start: yarn serve
  #         wait-on: http://localhost:9000

  # axe:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js 14.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  #     - run: npm install
  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run serve & npx wait-on http://localhost:9000
  #     - name: Run axe
  #       run: |
  #         npm install -g @axe-core/cli
  #         axe http://localhost:9000 --exit
